### ISSUE TITLE
Incorrect JSON-stat to dataframe parsing with ONS API

### ISSUE THREAD

**Issue by coriemiller** [predicador37/pyjstat#12]
Hello! I'm working with the UK Office of National Statistics API. 

http://web.ons.gov.uk/ons/api/data/dataset/A02Level.json?context=Economic&jsontype=json-stat&apikey={API_KEY_HERE}&geog=2011STATH&diff=&totals=false

Below is a portion of the response, showing information about the dimensions. Notice the un-sorted index and label keys/values. For example,

```   

{"A02Level": { 
"value" : {...},
"dimension" : {
    "id": {...},
    "size": {...},
    "role":{...},
    "CL_0001271": {
      "category": {
        "index": {
          "CI_0018949": 2,
          "CI_0018948": 3,
          "CI_0018944": 1,
          "CI_0018932": 0
          },
        "label": {
          "CI_0018949": "Economically Active",
          "CI_0018948": "Economically Inactive",
          "CI_0018944": "Unemployed",
          "CI_0018932": "In Employment"
          }
     },
"label": "Economic Status"
}, ... }}}}
```

The code below successfully parses the response to a CSV, but the wrong dimensions get attached to the values.
 ```
url = "http://web.ons.gov.uk/ons/api/data/dataset/A02Level.json?context=Economic&jsontype=json-stat&apikey={API_KEY_HERE}&geog=2011STATH&diff=&totals=false"
data = requests.get(url)
results = pyjstat.from_json_stat(data.json(object_pairs_hook=OrderedDict))
results[0].to_csv('results.csv')    
```

File:
![image](https://cloud.githubusercontent.com/assets/16008818/18879361/fd9559b4-84a1-11e6-858e-7ebd8fabd140.png)

According to the ONS data explorer, the dimensions for those values should be:
![](http://image.prntscr.com/image/c578d9d1b76b440d8b0f83c2071bdd53.png)

I've played with various permutations of sorting the keys/values of "index" and "label", but I arrive at the same incorrect CSV output each time.
```
data = requests.get(url)
jsondata = data.json(object_pairs_hook=OrderedDict)
ids = jsondata['A02Level']['dimension']['id']
for each_id in ids:
        temp_indexes = OrderedDict(sorted(jsondata['A02Level']['dimension'][each_id]['category']['index'].items(), key=lambda t: t[0]))
        jsondata['A02Level']['dimension'][each_id]['category']['index'] = temp_indexes
        try:
            temp_labels = OrderedDict(sorted(jsondata['A02Level']['dimension'][each_id]['category']['label'].items(), key=lambda t: t[0]))
            jsondata['A02Level']['dimension'][each_id]['category']['label'] = temp_labels
        except KeyError:
            pass
json_string = json.dumps(jsondata)
results = pyjstat.from_json_stat(json.loads(json_string))
results[0].to_csv('results_sorted_keys.csv')
```
Any ideas for a workaround?

**Comment by coriemiller** [comment]
Thanks so much!

**Comment by predicador37** [comment]
As I expected, the library is supposing that categories inside dimensions are ordered, and this doesn't have to be true. Ordering categories by index when converted to dataframe should fix it. I have a preliminar fix that produces the correct results. Maybe I can commit the patch tomorrow.

Thanks again for opening this so well reported issue.

**Comment by coriemiller** [comment]
Wonderful, looking forward to it- I appreciate the quick response!

**Comment by predicador37** [comment]
Hi, @coriemiller :

I think the bug should be fixed now. Thanks a lot for opening the issue again, this was a big one.

Sorry for the delay, it was a little bit tricker and my time was lesser than I thought... I've added a new test case with your dataset.

**Comment by coriemiller** [comment]
Thank you- it's working on my end! FYI- I'm noticing some console warnings when running- but the output is correct! Thanks again for fixing so quickly.

```
/Users/cmiller/GoogleDrive/local/kettle/etl/ons/ons/lib/python2.7/site-packages/pyjstat/pyjstat.py:178: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  dim_label = pd.merge(dim_label, dim_index, on='id').sort('index')
/Users/cmiller/GoogleDrive/local/kettle/etl/ons/ons/lib/python2.7/site-packages/pyjstat/pyjstat.py:211: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  dim_index = dim_index.sort('index')
```
