### ISSUE TITLE
Dead link in readme

### ISSUE THREAD

**Issue by tools4origins** [predicador37/pyjstat#14]
https://json-stat.org/samples/us-labor-ds.json used in the [Usage section](https://github.com/predicador37/pyjstat#usage) of the README returns a `Page not found` error.

**Comment by badosa** [comment]
At some point (sorry for that) the name of all the samples files was normalized. The new URL is

http://json-stat.org/samples/us-labor.json

The current URL of all the sample files can be retrieved browsing from 

http://json-stat.org/samples/

(this end point returns a JSON-stat collection)

**Comment by predicador37** [comment]
Thanks a lot both @tools4origins and @badosa 

Fixed by 8ab1fee629b80fe636462494f5de5d5d6629cd08
