### ISSUE TITLE
dataset.write('dataframe') deprecation warning (pandas)

### ISSUE THREAD

**Issue by Trollgeir** [predicador37/pyjstat#25]
pyjstat.py:250: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)
  dim_label = pd.merge(dim_label, dim_index, on='id').sort_index(by='index')

Tested using pandas version 0.25.1

**Comment by predicador37** [comment]
This should be fixed with pyjstat 2.0. Thanks for your patience.
