### ISSUE TITLE
DataFrame conversion not working

### ISSUE THREAD

**Issue by rezpe** [predicador37/pyjstat#3]
Hi,

   First thing: Your lirary is great, keep up with the good work. I am trying to use your lib to create JSON Stat Web services, but there's a problem in the dataframe to JSON stat conversion:
If you execute this code, you'll see the problem:

```python
from pyjstat import pyjstat
import urllib2
import json

results = pyjstat.from_json_stat(json.load(urllib2.urlopen(
                         'http://json-stat.org/samples/oecd-canada.json')))
intermediary = pyjstat.to_json_stat(results)
print  pyjstat.from_json_stat(intermediary)
--> Error: TypeError: string indices must be integers, not str
```

**Comment by predicador37** [comment]
I see what's happening here. Function to_json_stat() is returning a list of dicts, whereas original input is a dict of dicts. I think the right fix would be this:

- Modify to_json_stat() to return a dict of dicts instead a list of dicts
- Modify from_json_stat() to accept a list of dicts as input too

First change is straightforward and the second shouldn't be difficult. I'll try to commit the fixes ASAP.

Thanks for your feedback!

**Comment by predicador37** [comment]
Just a clafirication:

Your code should look like this:

    from pyjstat import pyjstat
    import urllib2
    import json
    from collections import OrderedDict

    data = json.load(urllib2.urlopen(
        'http://json-stat.org/samples/oecd-canada.json'),
        object_pairs_hook=OrderedDict)
    dataframes = pyjstat.from_json_stat(data)
    intermediary = json.loads(pyjstat.to_json_stat(dataframes),
                              object_pairs_hook=OrderedDict)
    print pyjstat.from_json_stat(intermediary)

I.e., you should use ordered dicts if you want to preserve the original order. Also, don't forget that `from_json_stat()` accepts JSON, so you should use json.loads with the output of `to_json_stat`, which is only a String dump.

Please, let me know if you can run your code. Also, I'd be interested in taking a look at your web service once it is finished, if you don't mind... Always glad to see that pyjstat is useful ;-)

**Comment by rezpe** [comment]
Hi, I have tried and I have a strange result:

```python
from pyjstat import pyjstat
import urllib2
import json
​
results = pyjstat.from_json_stat(json.load(urllib2.urlopen('http://json-stat.org/samples/oecd-canada.json')))
intermediary = pyjstat.to_json_stat(results)
pyjstat.from_json_stat(intermediary)
Output: []
```

**Comment by rezpe** [comment]
Also, please note that python and libraries are updated to the latest version.

**Comment by rezpe** [comment]
This fix works :)

**Comment by rezpe** [comment]
Thanks a lot for your work. However, I see a problem when retrieving the data from the Web Service. This is the code of the Web Service: The variable result is a previously created dataframe (the idea being that the WS is compliant with any Dataframe)

```python
from flask import Flask
from flask.ext import restful
import pandas as pd
from flask import request
from pyjstat import pyjstat
import json
    
app = Flask(__name__)
api = restful.Api(app)
 
class pandarequest(restful.Resource):
    def get(self):
        return json.loads(pyjstat.to_json_stat(result))
 
api.add_resource(pandarequest, '/api/invfiles')
 
if __name__ == '__main__':
    app.run(host="0.0.0.0",port=8089)
```

When retrieving the json response in the Web App, the Javascript JSON stat library can not retrieve the dimensions value. I guess the problem is that the index values should be integer, but are stored as strings. What do you think ?

**Comment by rezpe** [comment]
Thanks a lot for your work. But it is not still working. I think I have found the problem. If you look at the example dataframe: http://json-stat.org/samples/oecd-canada.json , you can see that the index of the category of a dimension is an integer and not a String.

``` javascript
"year" : {
				"label" : "2003-2014",
				"category" : {
					"index" : {
						"2003" : 0,
						"2004" : 1,
						"2005" : 2,
						"2006" : 3,
						"2007" : 4,
						"2008" : 5,
						"2009" : 6,
						"2010" : 7,
						"2011" : 8,
						"2012" : 9,
						"2013" : 10,
						"2014" : 11
					}
				}
			}
```

Your library returns strings for the index. It works in python but as soon you parse your output in Javascript, there are problems. Please can you modify or hint how to modify your code to be able to output index as integers ? 

Thanks a lot
