### ISSUE TITLE
Index in Dimensions

### ISSUE THREAD

**Issue by rezpe** [predicador37/pyjstat#4]
Thanks a lot for your work. But it is not still working. I think I have found the problem. If you look at the example dataframe: http://json-stat.org/samples/oecd-canada.json , you can see that the index of the category of a dimension is an integer and not a String.

``` javascript
"year" : {
				"label" : "2003-2014",
				"category" : {
					"index" : {
						"2003" : 0,
						"2004" : 1,
						"2005" : 2,
						"2006" : 3,
						"2007" : 4,
						"2008" : 5,
						"2009" : 6,
						"2010" : 7,
						"2011" : 8,
						"2012" : 9,
						"2013" : 10,
						"2014" : 11
					}
				}
			}
```

Your library returns strings for the index. 

```javascript
"2003-2014": {
          "category": {
            "index": {
              "2003": "0",
              "2004": "1",
              "2005": "2",
              "2006": "3",
              "2007": "4",
              "2008": "5",
              "2009": "6",
              "2010": "7",
              "2011": "8",
              "2012": "9",
              "2013": "10",
              "2014": "11"
            }
```

It works in python but as soon you parse your output in Javascript, there are problems. Please can you modify or hint how to modify your code to be able to output index as integers ? 

Thanks a lot

**Comment by rezpe** [comment]
Also please see below code of the Web Service, which is very simple:

**Comment by rezpe** [comment]
After further investigation, the problem seems to be in the label of the dimensions. If removed, the values are properly read by the JSON Stat Javascript libraries (I mean removing the "label" array inside the "category" object of the dimension.)

**Comment by predicador37** [comment]
mmm I see your point. I fixed this time ago, but never committed the changes. It's as easy as using a function which decides the output type (string or int) depending on the examined variable. Give me some time to put some tests to work and tomorrow I'll have it solved.

Thanks a lot for your feedback again!

**Comment by rezpe** [comment]
No problem, also check the Gist so you can see how your library is put to good use :):
https://gist.github.com/rezpe/2654be0d6810acd655f5

**Comment by rezpe** [comment]
As said previously, there's also a problem with the label. If I remove it, the JSON is correctly parsed.

**Comment by predicador37** [comment]
I've been re-reading json-stat format documentation. The behaviour with my upcoming fix will be the following:

- If the variable is an index, integer values will be output as integer values.
- If the variable a label, integer values will be output as strings.

If you remove the label, JSON-stat default behaviour will be using the index as label. From the docs: *When no category labels are provided, the recommended behavior for a JSON-stat client is to use the IDs (as they appear in index) as labels. In this case, IDs should be chosen wisely.*

I cannot test the fix against Javascript code ATM, but should be OK...

**Comment by rezpe** [comment]
Thanks, I will test the fix. Also you can test the javascript with nodejs:
https://github.com/badosa/JSON-stat/blob/master/nodejs.js
If you need any help, let me know.

**Comment by predicador37** [comment]
Solved by 5ebbd4fa0149b5173a1fe4050835a8d42248ec1c

**Comment by rezpe** [comment]
Great !!!! All solved. I tested it against javascript as well and it works flawlessly for my case :)

**Comment by predicador37** [comment]
I'm glad it works now. I hope I can improve the library in the future.

Thanks again for your feedback!
