### ISSUE TITLE
Simple DataFrame not working

### ISSUE THREAD

**Issue by rezpe** [predicador37/pyjstat#5]
I have been trying the library with a dataframe created from this simple csv

```csv
,EANHotelID,SequenceNumber,Name,Address1,Address2,City,StateProvince,PostalCode,Country,Latitude,Longitude,AirportCode,PropertyCategory,PropertyCurrency,StarRating,Confidence,SupplierType,Location,ChainCodeID,RegionID,HighRate,LowRate,CheckInTime,CheckOutTime,value
1,350924,1,Iberostar Paraiso Beach All Inclusive,Carretera Chetumal,"Puerto Juarez, Km.309",Playa del Carmen,,77710,MX,20.76303,-86.96769,CUN,8,MXN,3.5,52.0,ESR,Near Maroma Beach,2227.0,601751,1098.6801,938.68,3 PM,noon,6
2,272355,2,The Regent Grand on Grace Bay Beach,Regent Street,,Providenciales,,NA,TC,21.79609,-72.18029,PLS,3,USD,4.5,52.0,ESR,In Providenciales (Grace Bay),,2822,2896.49,2895.49,3 PM,11 AM,6
3,313805,3,Lindos Imperial - All Inclusive,Kiotari,,Rhodes,,85109,GR,36.06391,27.98944,RHO,1,EUR,5.0,52.0,ESR,Near Kiotari Beach,,11286,298.2491,297.2491,2 PM,noon,8
4,226126,4,Sani Beach Club,Sani,Halkidiki,Kassandra,,63077,GR,40.09592,23.31255,SKG,1,EUR,5.0,52.0,ESR,In Kassandra (Halkidiki),,180586,766.2162,765.2162,2 PM,noon,3
5,230336,5,Bora Bora Eden Beach Hotel,Motu Pitiaau,,Bora Bora,,98730,PF,-16.51928,-151.70398,BOB,3,XPF,2.5,52.0,ESR,In Bora Bora (Motu Piti Aau),,602862,504.743,353.0016,1 PM,11 AM,4
6,169531,6,The Fairmont Hamilton Princess,76 Pitts Bay Road,,Pembroke,,HM 08,BM,32.29136,-64.79195,BDA,3,USD,4.0,95.0,ESR,Near Albuoy's Point Park,209.0,12156,559.0,369.0,3 PM,noon,4
7,127144,7,Four Seasons Resort Lanai at Manele Bay,1 Manele Bay Road,,Lanai City,HI,96763,US,20.74241,-156.89678,LNY,3,USD,5.0,52.0,ESR,Near Manele Golf Course,2130.0,2109,3750.0,900.0,3 PM,Noon,6
8,261444,8,Extended Stay America Fort Lauderdale - Cypress Crk -6th Way,6001 Nw 6th Way,,Fort Lauderdale,FL,33309,US,26.20197,-80.15259,FLL,1,USD,2.5,60.0,ESR,In Fort Lauderdale (North Fort Lauderdale),2074.0,1219,169.99,159.99,3 PM,11 AM,8
9,188379,9,Riu Palace Mexico All Inclusive,"Avda. Xaman-Ha, Manzana 3, Lote 4",Condominio Playacar,Playa del Carmen,,77710,MX,20.60767,-87.09244,CUN,8,MXN,4.0,52.0,ESR,Near Playacar Golf Club,2578.0,601751,677.09,651.63,3 PM,noon,3
```

Then while converting and getting the dataframe back, I get this error:

```python
response = pd.read_csv("test.csv")
result = pyjstat.to_json_stat(response)
pyjstat.from_json_stat(json.loads(result))
#Error IndexError: pop from empty list
```

**Comment by predicador37** [comment]
This is a more serious bug, related to the null values. Conversion to JSON with nulls is not working properly, definitely. I'll try to fix it ASAP.

You're getting me a lot of bugs here... thanks for your beta testing. It's helping a lot to improve the library.

**Comment by predicador37** [comment]
Most precisely, the problem are repeated null dimension values; an empty key is possible, but most JSON libraries don't allow duplicated keys.

I'm thinking about removing all empty/null dimension values in the JSON export and then handle them some way at the JSON to dataframe conversion.

**Comment by rezpe** [comment]
I guess you are right. This also relates to the classical dimension vs measure thing. In the csv, those are the columns and their classification, Does this mean that we should create 1 dataframe per measure ? Isn't it a bit overkill ?

```csv
Dimensions:
EANHotelID,
SequenceNumber,
Name,
Address1,
Address2,
City,
StateProvince,
PostalCode,
Country,
Latitude,
Longitude,
AirportCode,
PropertyCategory,
PropertyCurrency,
SupplierType,
Location,
ChainCodeID,
RegionID

Measures
StarRating,
Confidence,
HighRate,
LowRate,
CheckInTime,
CheckOutTime
```

**Comment by predicador37** [comment]
Perhaps it is redundant, but note that JSON-stat is a lightweight format thought for mobile apps too, and including a lot of categories, dimensions and measures maybe would be too much weight. Anyway, this would be a format limitation which cannot be fixed by a simple conversion library. 

Some more info about dimensions and categories order from the docs :

>The order of the categories and the order of the dimensions themselves determine the order of the data in the value array. While the dimensions’ order has only this functional role (and therefore any order chosen by the provider is valid), the categories’ order has also a presentation role: it is assumed that the categories are sorted in a meaningful order and that the consumer can rely on it when displaying the information. For example, categories in dimensions with a time role are assumed to be in chronological order.

I guess I could code some checks for the order of the input dataframe, but data normalization and cleansing tasks should be performed before putting them into a dissemination library.
