### ISSUE TITLE
Forced conversion to numeric

### ISSUE THREAD

**Issue by klpn** [predicador37/pyjstat#9]
On [line 299 in `pyjstat.py`](https://github.com/predicador37/pyjstat/blob/master/pyjstat/pyjstat.py#L299), you have `convert_numeric=True`. Thus, when a DataFrame is generated from a JSON-stat dict, Pandas attempts to coerce e.g. strings to numbers. I have a dataset downloaded from Statistics Sweden, where the first lines in a column are zeros, followed by strings containing e.g. dashes. So, when I call `from_json_stat`, these latter lines become `NaN`, because they cannot be coerced to numbers. If I set `convert_numeric=False` in the source code, the column is imported correctly. Maybe the coercion to numbers should be made optional? (Besides, Pandas gives the following message when `from_json_stat` is called: `FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric_objects`.)

**Comment by predicador37** [comment]
Mmmm you've got a point... Whatever reason I had to coerce to number there,
it should be an optional parameter in any case.

Let me take a look and I'll fix and update the code.

Thanks a lot for your input!

2015-11-22 17:16 GMT+01:00 Karl Pettersson <notifications@github.com>:

> On line 299 in pyjstat.py
> <https://github.com/predicador37/pyjstat/blob/master/pyjstat/pyjstat.py#L299>,
> you have convert_numeric=True. Thus, when a DataFrame is generated from a
> JSON-stat dict, Pandas attempts to coerce e.g. strings to numbers. I have a
> dataset downloaded from Statistics Sweden, where the first lines in a
> column are zeros, followed by strings containing e.g. dashes. So, when I
> call from_json_stat, these latter lines become NaN, because they cannot
> be coerced to numbers. If I set convert_numeric=False in the source code,
> the column is imported correctly. Maybe the coercion to numbers should be
> made optional? (Besides, Pandas gives the following message when
> from_json_stat is called: FutureWarning: convert_objects is deprecated.
> Use the data-type specific converters pd.to_datetime, pd.to_timedelta and
> pd.to_numeric_objects.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/predicador37/pyjstat/issues/9>.
>



-- 
<http://about.me/predicador37>
[image: Miguel Expósito on about.me]

Miguel Expósito
about.me/predicador37
  <http://about.me/predicador37>

**Comment by predicador37** [comment]
Hi, @klpn , could you provide the URL of your dataset? I'd like to check something and include it in the pyjstat test suite.  Thanks in advance.

**Comment by klpn** [comment]
POST e.g. [this JSON](https://gist.github.com/klpn/df58bd3c9c07fd06ed1b) to `http://api.scb.se/OV0104/v1/doris/sv/ssd/START/HS/HS0301/DodaOrsak` in order to make a query. If the response content is converted with `from_json_stat` (and `naming = id`), most of the lines in the `Alder` ("Age") column in the dataset become `NaN` if `convert_numeric=True`.

**Comment by predicador37** [comment]
Hi, @klpn 

After checking the code, I've come to the conclusion that this conversion is not needed. Probably I simply forgot to remove it. Also, I've fixed a bug that converted zero values into nulls in the to_json() method. I've included your JSON as a test case, and it should work fine now.

Thanks a lot for contributing!
